// Generated by tools/build-face-atlas.py - do not edit.
// Slot of each hero's idle face in images/chars/faces-a.png (8x8 grid of 128px).

export const FACE_ATLAS_SRC = 'images/chars/faces-a.png'
export const FACE_GRID = 8

export const FACE_SLOT: Record<string, number> = {
  hallwarden: 0,
  'sigil-witch': 1,
  crowmark: 2,
  blaze: 3,
  rook: 4,
  voss: 5,
  kite: 6,
  hexa: 7,
  siphon: 8,
  lyra: 9,
  pax: 10,
  garr: 11,
  nova: 12,
  'ash-hound': 13,
  'cinder-wight': 14,
  'lamp-imp': 15,
  'moor-ogre': 16,
  'moor-crow': 17,
  'grave-pike': 18,
  'rust-ballista': 19,
  'thorn-queen': 20,
  'veil-sister': 21,
  'blood-leech': 22,
  'dusk-oracle': 23,
  'crimson-abbot': 24,
  'oath-knight': 25,
  'night-covenant': 26,
  'pale-howl': 27,
  'ashen-regent': 28,
  'frost-monarch': 29,
  'ether-assassin': 30,
  'wasteland-monarch': 31
}
