// AUTO-GENERATED by tools/gen-duel-labels.ps1 -- do not edit by hand.
// Friendzone duel word strips. Importing this module registers them into LABELS.
// One PNG per strip (see lib-labels.ps1 for why not an atlas).
import { LABELS, LabelInfo } from './labels.gen'

export const DUEL_LABELS: Record<string, LabelInfo> = {
  raids: { src: 'images/labels/raids.png', w: 66, h: 145 },
  duels: { src: 'images/labels/duels.png', w: 66, h: 152 },
  victor: { src: 'images/labels/victor.png', w: 66, h: 174 },
  'duel-1v1': { src: 'images/labels/duel-1v1.png', w: 66, h: 146 },
  'duel-4v4': { src: 'images/labels/duel-4v4.png', w: 66, h: 146 },
  leaderboard: { src: 'images/labels/leaderboard.png', w: 57, h: 285 },
  wins: { src: 'images/labels/wins.png', w: 49, h: 98 },
  'player-vs-player': { src: 'images/labels/player-vs-player.png', w: 57, h: 352 },
  'awaiting-foe': { src: 'images/labels/awaiting-foe.png', w: 57, h: 492 },
  'duel-cost': { src: 'images/labels/duel-cost.png', w: 57, h: 509 },
  'duel-cost4': { src: 'images/labels/duel-cost4.png', w: 57, h: 509 },
  'need-four': { src: 'images/labels/need-four.png', w: 57, h: 767 },
  'join-duel': { src: 'images/labels/join-duel.png', w: 66, h: 332 },
  'join-raid': { src: 'images/labels/join-raid.png', w: 66, h: 324 },
  'pick-your-champion': { src: 'images/labels/pick-your-champion.png', w: 57, h: 726 },
  'tap-join-party': { src: 'images/labels/tap-join-party.png', w: 57, h: 594 },
  'tap-enter-ready': { src: 'images/labels/tap-enter-ready.png', w: 57, h: 471 },
  'foe-not-ready': { src: 'images/labels/foe-not-ready.png', w: 57, h: 447 }
}

Object.assign(LABELS, DUEL_LABELS)
