// AUTO-GENERATED by tools/gen-story-labels.ps1 -- do not edit by hand.
// Road-story / final-battle / epilogue narrator strips, pre-rotated like
// every other label. Importing this module registers them into LABELS.
import { LABELS, LabelInfo } from './labels.gen'

export const STORY_LABELS: Record<string, LabelInfo> = {
  'story-q1-1a': { src: 'images/labels/story-q1-1a.png', w: 38, h: 565 },
  'story-q1-1b': { src: 'images/labels/story-q1-1b.png', w: 38, h: 504 },
  'story-q1-1c': { src: 'images/labels/story-q1-1c.png', w: 38, h: 611 },
  'story-q1-2a': { src: 'images/labels/story-q1-2a.png', w: 38, h: 558 },
  'story-q1-2b': { src: 'images/labels/story-q1-2b.png', w: 38, h: 475 },
  'story-q1-2c': { src: 'images/labels/story-q1-2c.png', w: 38, h: 414 },
  'story-q3-1a': { src: 'images/labels/story-q3-1a.png', w: 38, h: 572 },
  'story-q3-1b': { src: 'images/labels/story-q3-1b.png', w: 38, h: 601 },
  'story-q3-1c': { src: 'images/labels/story-q3-1c.png', w: 38, h: 536 },
  'story-q3-2a': { src: 'images/labels/story-q3-2a.png', w: 38, h: 629 },
  'story-q3-2b': { src: 'images/labels/story-q3-2b.png', w: 38, h: 525 },
  'story-q3-2c': { src: 'images/labels/story-q3-2c.png', w: 38, h: 488 },
  'story-q4-1a': { src: 'images/labels/story-q4-1a.png', w: 38, h: 581 },
  'story-q4-1b': { src: 'images/labels/story-q4-1b.png', w: 38, h: 490 },
  'story-q4-1c': { src: 'images/labels/story-q4-1c.png', w: 38, h: 459 },
  'story-q4-2a': { src: 'images/labels/story-q4-2a.png', w: 38, h: 577 },
  'story-q4-2b': { src: 'images/labels/story-q4-2b.png', w: 38, h: 560 },
  'story-q4-2c': { src: 'images/labels/story-q4-2c.png', w: 38, h: 484 },
  'story-q6-1a': { src: 'images/labels/story-q6-1a.png', w: 38, h: 570 },
  'story-q6-1b': { src: 'images/labels/story-q6-1b.png', w: 38, h: 410 },
  'story-q6-1c': { src: 'images/labels/story-q6-1c.png', w: 38, h: 539 },
  'story-q6-2a': { src: 'images/labels/story-q6-2a.png', w: 38, h: 515 },
  'story-q6-2b': { src: 'images/labels/story-q6-2b.png', w: 38, h: 345 },
  'story-q6-2c': { src: 'images/labels/story-q6-2c.png', w: 38, h: 403 },
  'story-final-1a': { src: 'images/labels/story-final-1a.png', w: 38, h: 483 },
  'story-final-1b': { src: 'images/labels/story-final-1b.png', w: 38, h: 566 },
  'story-final-1c': { src: 'images/labels/story-final-1c.png', w: 38, h: 470 },
  'story-final-2a': { src: 'images/labels/story-final-2a.png', w: 38, h: 570 },
  'story-final-2b': { src: 'images/labels/story-final-2b.png', w: 38, h: 440 },
  'story-final-2c': { src: 'images/labels/story-final-2c.png', w: 38, h: 457 },
  'story-epilogue-1a': { src: 'images/labels/story-epilogue-1a.png', w: 38, h: 531 },
  'story-epilogue-1b': { src: 'images/labels/story-epilogue-1b.png', w: 38, h: 502 },
  'story-epilogue-1c': { src: 'images/labels/story-epilogue-1c.png', w: 38, h: 518 },
  'story-epilogue-2a': { src: 'images/labels/story-epilogue-2a.png', w: 38, h: 481 },
  'story-epilogue-2b': { src: 'images/labels/story-epilogue-2b.png', w: 38, h: 358 },
  'story-epilogue-2c': { src: 'images/labels/story-epilogue-2c.png', w: 38, h: 405 },
  'story-final-name': { src: 'images/labels/story-final-name.png', w: 38, h: 302 }
}

Object.assign(LABELS, STORY_LABELS)
