// AUTO-GENERATED by tools/gen-intro-labels.ps1 -- do not edit by hand.
// Intro story narrator line strips, pre-rotated like every other label.
// Importing this module registers them into the shared LABELS map.
import { LABELS, LabelInfo } from './labels.gen'

export const INTRO_LABELS: Record<string, LabelInfo> = {
  'intro-1a': { src: 'images/labels/intro-1a.png', w: 76, h: 774 },
  'intro-1b': { src: 'images/labels/intro-1b.png', w: 76, h: 867 },
  'intro-2a': { src: 'images/labels/intro-2a.png', w: 76, h: 810 },
  'intro-2b': { src: 'images/labels/intro-2b.png', w: 76, h: 1017 },
  'intro-2c': { src: 'images/labels/intro-2c.png', w: 76, h: 856 },
  'intro-3a': { src: 'images/labels/intro-3a.png', w: 76, h: 652 },
  'intro-3b': { src: 'images/labels/intro-3b.png', w: 76, h: 885 },
  'intro-3c': { src: 'images/labels/intro-3c.png', w: 76, h: 1191 },
  'intro-4a': { src: 'images/labels/intro-4a.png', w: 76, h: 784 },
  'intro-4b': { src: 'images/labels/intro-4b.png', w: 76, h: 957 },
  'intro-4c': { src: 'images/labels/intro-4c.png', w: 76, h: 950 },
  'intro-4d': { src: 'images/labels/intro-4d.png', w: 76, h: 1063 },
  'intro-5a': { src: 'images/labels/intro-5a.png', w: 76, h: 737 },
  'intro-5b': { src: 'images/labels/intro-5b.png', w: 76, h: 848 },
  'intro-5c': { src: 'images/labels/intro-5c.png', w: 76, h: 787 },
  'intro-5d': { src: 'images/labels/intro-5d.png', w: 76, h: 511 },
  'intro-6a': { src: 'images/labels/intro-6a.png', w: 76, h: 1273 },
  'intro-6b': { src: 'images/labels/intro-6b.png', w: 76, h: 1147 },
  'intro-6c': { src: 'images/labels/intro-6c.png', w: 76, h: 459 },
  'intro-6d': { src: 'images/labels/intro-6d.png', w: 76, h: 880 },
  'intro-w1': { src: 'images/labels/intro-w1.png', w: 76, h: 871 },
  'intro-w2': { src: 'images/labels/intro-w2.png', w: 76, h: 1010 },
  'intro-w3': { src: 'images/labels/intro-w3.png', w: 76, h: 763 },
  'intro-f1': { src: 'images/labels/intro-f1.png', w: 76, h: 1284 },
  'intro-f2': { src: 'images/labels/intro-f2.png', w: 76, h: 1119 },
  'intro-f3': { src: 'images/labels/intro-f3.png', w: 76, h: 1247 },
  'intro-f4': { src: 'images/labels/intro-f4.png', w: 76, h: 914 },
  'intro-f5': { src: 'images/labels/intro-f5.png', w: 76, h: 1228 },
  'intro-f6': { src: 'images/labels/intro-f6.png', w: 76, h: 793 },
  'intro-f7': { src: 'images/labels/intro-f7.png', w: 76, h: 995 },
  'intro-f8': { src: 'images/labels/intro-f8.png', w: 76, h: 1098 },
  'intro-d1': { src: 'images/labels/intro-d1.png', w: 76, h: 935 },
  'intro-d2': { src: 'images/labels/intro-d2.png', w: 76, h: 873 },
  'intro-d3': { src: 'images/labels/intro-d3.png', w: 76, h: 516 }
}

Object.assign(LABELS, INTRO_LABELS)
