// AUTO-GENERATED by tools/gen-credits-labels.ps1 -- do not edit by hand.
// Credits-roll line strips, pre-rotated like every other label. Importing
// this module registers them into the shared LABELS map.
import { LABELS, LabelInfo } from './labels.gen'

export const CREDITS_LABELS: Record<string, LabelInfo> = {
  'credits-created': { src: 'images/labels/credits-created.png', w: 38, h: 158 },
  'credits-matt': { src: 'images/labels/credits-matt.png', w: 38, h: 81 },
  'credits-role': { src: 'images/labels/credits-role.png', w: 38, h: 454 },
  'credits-voice': { src: 'images/labels/credits-voice.png', w: 38, h: 229 },
  'credits-eleven': { src: 'images/labels/credits-eleven.png', w: 38, h: 161 },
  'credits-art': { src: 'images/labels/credits-art.png', w: 38, h: 135 },
  'credits-art2': { src: 'images/labels/credits-art2.png', w: 38, h: 422 },
  'credits-built': { src: 'images/labels/credits-built.png', w: 38, h: 151 },
  'credits-sdk': { src: 'images/labels/credits-sdk.png', w: 38, h: 280 },
  'credits-for': { src: 'images/labels/credits-for.png', w: 38, h: 135 },
  'credits-regenesis': { src: 'images/labels/credits-regenesis.png', w: 38, h: 209 },
  'credits-buildathon': { src: 'images/labels/credits-buildathon.png', w: 38, h: 339 },
  'credits-starring': { src: 'images/labels/credits-starring.png', w: 38, h: 134 },
  'credits-warlords': { src: 'images/labels/credits-warlords.png', w: 38, h: 280 },
  'credits-tale': { src: 'images/labels/credits-tale.png', w: 38, h: 262 },
  'credits-thanks': { src: 'images/labels/credits-thanks.png', w: 38, h: 280 },
  'credits-fire': { src: 'images/labels/credits-fire.png', w: 38, h: 497 }
}

Object.assign(LABELS, CREDITS_LABELS)
