// AUTO-GENERATED by tools/gen-daily-labels.ps1 -- do not edit by hand.
// Events-page daily word strips (login streak + task board). Importing this module registers them into LABELS.
// One PNG per strip (see lib-labels.ps1 for why not an atlas).
import { LABELS, LabelInfo } from './labels.gen'

export const DAILY_LABELS: Record<string, LabelInfo> = {
  'daily-rewards': { src: 'images/labels/daily-rewards.png', w: 66, h: 362 },
  'daily-tasks': { src: 'images/labels/daily-tasks.png', w: 66, h: 283 },
  'task-go': { src: 'images/labels/task-go.png', w: 66, h: 84 },
  streak: { src: 'images/labels/streak.png', w: 57, h: 151 },
  day: { src: 'images/labels/day.png', w: 57, h: 92 },
  claim: { src: 'images/labels/claim.png', w: 66, h: 152 },
  claimed: { src: 'images/labels/claimed.png', w: 57, h: 180 },
  'come-back-tomorrow': { src: 'images/labels/come-back-tomorrow.png', w: 57, h: 480 },
  'streak-hint': { src: 'images/labels/streak-hint.png', w: 49, h: 685 },
  'streak-lost': { src: 'images/labels/streak-lost.png', w: 49, h: 536 },
  'new-tasks-in': { src: 'images/labels/new-tasks-in.png', w: 49, h: 237 },
  'all-done-bonus': { src: 'images/labels/all-done-bonus.png', w: 57, h: 342 },
  'energy-refill': { src: 'images/labels/energy-refill.png', w: 49, h: 240 },
  'hero-card': { src: 'images/labels/hero-card.png', w: 49, h: 197 },
  today: { src: 'images/labels/today.png', w: 49, h: 121 },
  'page-dailies': { src: 'images/labels/page-dailies.png', w: 57, h: 152 },
  'page-realm': { src: 'images/labels/page-realm.png', w: 57, h: 222 },
  'task-floors': { src: 'images/labels/task-floors.png', w: 57, h: 437 },
  'task-wild': { src: 'images/labels/task-wild.png', w: 57, h: 458 },
  'task-pack': { src: 'images/labels/task-pack.png', w: 57, h: 263 },
  'task-fuse': { src: 'images/labels/task-fuse.png', w: 57, h: 360 },
  'task-raid': { src: 'images/labels/task-raid.png', w: 57, h: 353 },
  'task-duel': { src: 'images/labels/task-duel.png', w: 57, h: 266 },
  'task-gift': { src: 'images/labels/task-gift.png', w: 57, h: 359 },
  'task-trade': { src: 'images/labels/task-trade.png', w: 57, h: 377 }
}

Object.assign(LABELS, DAILY_LABELS)
