// AUTO-GENERATED by tools/gen-credits-labels.ps1 -- do not edit by hand.
// Credits-roll line strips, pre-rotated like every other label. Importing
// this module registers them into the shared LABELS map.
import { LABELS, LabelInfo } from './labels.gen'

export const CREDITS_LABELS: Record<string, LabelInfo> = {
  'credits-created': { src: 'images/labels/credits-created.png', w: 76, h: 314 },
  'credits-matt': { src: 'images/labels/credits-matt.png', w: 76, h: 159 },
  'credits-role': { src: 'images/labels/credits-role.png', w: 76, h: 906 },
  'credits-voice': { src: 'images/labels/credits-voice.png', w: 76, h: 456 },
  'credits-eleven': { src: 'images/labels/credits-eleven.png', w: 76, h: 319 },
  'credits-art': { src: 'images/labels/credits-art.png', w: 76, h: 268 },
  'credits-art2': { src: 'images/labels/credits-art2.png', w: 76, h: 842 },
  'credits-built': { src: 'images/labels/credits-built.png', w: 76, h: 300 },
  'credits-sdk': { src: 'images/labels/credits-sdk.png', w: 76, h: 557 },
  'credits-for': { src: 'images/labels/credits-for.png', w: 76, h: 268 },
  'credits-regenesis': { src: 'images/labels/credits-regenesis.png', w: 76, h: 415 },
  'credits-buildathon': { src: 'images/labels/credits-buildathon.png', w: 76, h: 675 },
  'credits-starring': { src: 'images/labels/credits-starring.png', w: 76, h: 266 },
  'credits-warlords': { src: 'images/labels/credits-warlords.png', w: 76, h: 558 },
  'credits-tale': { src: 'images/labels/credits-tale.png', w: 76, h: 521 },
  'credits-thanks': { src: 'images/labels/credits-thanks.png', w: 76, h: 558 },
  'credits-fire': { src: 'images/labels/credits-fire.png', w: 76, h: 991 }
}

Object.assign(LABELS, CREDITS_LABELS)
