// AUTO-GENERATED by tools/gen-story-labels.ps1 -- do not edit by hand.
// Road-story / final-battle / epilogue narrator strips, pre-rotated like
// every other label. Importing this module registers them into LABELS.
import { LABELS, LabelInfo } from './labels.gen'

export const STORY_LABELS: Record<string, LabelInfo> = {
  'story-q1-1a': { src: 'images/labels/story-q1-1a.png', w: 76, h: 1128 },
  'story-q1-1b': { src: 'images/labels/story-q1-1b.png', w: 76, h: 1005 },
  'story-q1-1c': { src: 'images/labels/story-q1-1c.png', w: 76, h: 1219 },
  'story-q1-2a': { src: 'images/labels/story-q1-2a.png', w: 76, h: 1114 },
  'story-q1-2b': { src: 'images/labels/story-q1-2b.png', w: 76, h: 947 },
  'story-q1-2c': { src: 'images/labels/story-q1-2c.png', w: 76, h: 825 },
  'story-q3-1a': { src: 'images/labels/story-q3-1a.png', w: 76, h: 1142 },
  'story-q3-1b': { src: 'images/labels/story-q3-1b.png', w: 76, h: 1200 },
  'story-q3-1c': { src: 'images/labels/story-q3-1c.png', w: 76, h: 1070 },
  'story-q3-2a': { src: 'images/labels/story-q3-2a.png', w: 76, h: 1256 },
  'story-q3-2b': { src: 'images/labels/story-q3-2b.png', w: 76, h: 1048 },
  'story-q3-2c': { src: 'images/labels/story-q3-2c.png', w: 76, h: 973 },
  'story-q4-1a': { src: 'images/labels/story-q4-1a.png', w: 76, h: 1159 },
  'story-q4-1b': { src: 'images/labels/story-q4-1b.png', w: 76, h: 978 },
  'story-q4-1c': { src: 'images/labels/story-q4-1c.png', w: 76, h: 916 },
  'story-q4-2a': { src: 'images/labels/story-q4-2a.png', w: 76, h: 1151 },
  'story-q4-2b': { src: 'images/labels/story-q4-2b.png', w: 76, h: 1117 },
  'story-q4-2c': { src: 'images/labels/story-q4-2c.png', w: 76, h: 966 },
  'story-q6-1a': { src: 'images/labels/story-q6-1a.png', w: 76, h: 1137 },
  'story-q6-1b': { src: 'images/labels/story-q6-1b.png', w: 76, h: 818 },
  'story-q6-1c': { src: 'images/labels/story-q6-1c.png', w: 76, h: 1076 },
  'story-q6-2a': { src: 'images/labels/story-q6-2a.png', w: 76, h: 1028 },
  'story-q6-2b': { src: 'images/labels/story-q6-2b.png', w: 76, h: 688 },
  'story-q6-2c': { src: 'images/labels/story-q6-2c.png', w: 76, h: 804 },
  'story-final-1a': { src: 'images/labels/story-final-1a.png', w: 76, h: 963 },
  'story-final-1b': { src: 'images/labels/story-final-1b.png', w: 76, h: 1130 },
  'story-final-1c': { src: 'images/labels/story-final-1c.png', w: 76, h: 938 },
  'story-final-2a': { src: 'images/labels/story-final-2a.png', w: 76, h: 1138 },
  'story-final-2b': { src: 'images/labels/story-final-2b.png', w: 76, h: 878 },
  'story-final-2c': { src: 'images/labels/story-final-2c.png', w: 76, h: 912 },
  'story-epilogue-1a': { src: 'images/labels/story-epilogue-1a.png', w: 76, h: 1059 },
  'story-epilogue-1b': { src: 'images/labels/story-epilogue-1b.png', w: 76, h: 1001 },
  'story-epilogue-1c': { src: 'images/labels/story-epilogue-1c.png', w: 76, h: 1034 },
  'story-epilogue-2a': { src: 'images/labels/story-epilogue-2a.png', w: 76, h: 960 },
  'story-epilogue-2b': { src: 'images/labels/story-epilogue-2b.png', w: 76, h: 713 },
  'story-epilogue-2c': { src: 'images/labels/story-epilogue-2c.png', w: 76, h: 808 },
  'story-final-name': { src: 'images/labels/story-final-name.png', w: 76, h: 602 }
}

Object.assign(LABELS, STORY_LABELS)
