// AUTO-GENERATED by tools/gen-intro-labels.ps1 -- do not edit by hand.
// Intro story narrator line strips, pre-rotated like every other label.
// Importing this module registers them into the shared LABELS map.
import { LABELS, LabelInfo } from './labels.gen'

export const INTRO_LABELS: Record<string, LabelInfo> = {
  'intro-1a': { src: 'images/labels/intro-1a.png', w: 38, h: 388 },
  'intro-1b': { src: 'images/labels/intro-1b.png', w: 38, h: 435 },
  'intro-2a': { src: 'images/labels/intro-2a.png', w: 38, h: 406 },
  'intro-2b': { src: 'images/labels/intro-2b.png', w: 38, h: 510 },
  'intro-2c': { src: 'images/labels/intro-2c.png', w: 38, h: 429 },
  'intro-3a': { src: 'images/labels/intro-3a.png', w: 38, h: 327 },
  'intro-3b': { src: 'images/labels/intro-3b.png', w: 38, h: 444 },
  'intro-3c': { src: 'images/labels/intro-3c.png', w: 38, h: 597 },
  'intro-4a': { src: 'images/labels/intro-4a.png', w: 38, h: 393 },
  'intro-4b': { src: 'images/labels/intro-4b.png', w: 38, h: 480 },
  'intro-4c': { src: 'images/labels/intro-4c.png', w: 38, h: 476 },
  'intro-4d': { src: 'images/labels/intro-4d.png', w: 38, h: 533 },
  'intro-5a': { src: 'images/labels/intro-5a.png', w: 38, h: 370 },
  'intro-5b': { src: 'images/labels/intro-5b.png', w: 38, h: 425 },
  'intro-5c': { src: 'images/labels/intro-5c.png', w: 38, h: 395 },
  'intro-5d': { src: 'images/labels/intro-5d.png', w: 38, h: 257 },
  'intro-6a': { src: 'images/labels/intro-6a.png', w: 38, h: 638 },
  'intro-6b': { src: 'images/labels/intro-6b.png', w: 38, h: 575 },
  'intro-6c': { src: 'images/labels/intro-6c.png', w: 38, h: 231 },
  'intro-6d': { src: 'images/labels/intro-6d.png', w: 38, h: 441 },
  'intro-w1': { src: 'images/labels/intro-w1.png', w: 38, h: 437 },
  'intro-w2': { src: 'images/labels/intro-w2.png', w: 38, h: 506 },
  'intro-w3': { src: 'images/labels/intro-w3.png', w: 38, h: 383 },
  'intro-f1': { src: 'images/labels/intro-f1.png', w: 38, h: 643 },
  'intro-f2': { src: 'images/labels/intro-f2.png', w: 38, h: 561 },
  'intro-f3': { src: 'images/labels/intro-f3.png', w: 38, h: 625 },
  'intro-f4': { src: 'images/labels/intro-f4.png', w: 38, h: 458 },
  'intro-f5': { src: 'images/labels/intro-f5.png', w: 38, h: 615 },
  'intro-f6': { src: 'images/labels/intro-f6.png', w: 38, h: 398 },
  'intro-f7': { src: 'images/labels/intro-f7.png', w: 38, h: 499 },
  'intro-f8': { src: 'images/labels/intro-f8.png', w: 38, h: 550 },
  'intro-d1': { src: 'images/labels/intro-d1.png', w: 38, h: 469 },
  'intro-d2': { src: 'images/labels/intro-d2.png', w: 38, h: 438 },
  'intro-d3': { src: 'images/labels/intro-d3.png', w: 38, h: 259 }
}

Object.assign(LABELS, INTRO_LABELS)
