// AUTO-GENERATED by tools/gen-wardrobe-labels.ps1 -- do not edit by hand.
// Tailor / wardrobe word strips and the tailor's talk lines. Importing this module registers them into LABELS.
// One PNG per strip (see lib-labels.ps1 for why not an atlas).
import { LABELS, LabelInfo } from './labels.gen'

export const WARDROBE_LABELS: Record<string, LabelInfo> = {
  'wardrobe-title': { src: 'images/labels/wardrobe-title.png', w: 57, h: 367 },
  'tab-colors': { src: 'images/labels/tab-colors.png', w: 57, h: 165 },
  'tab-clothes': { src: 'images/labels/tab-clothes.png', w: 57, h: 181 },
  'fit-villager': { src: 'images/labels/fit-villager.png', w: 49, h: 244 },
  'fit-ranger': { src: 'images/labels/fit-ranger.png', w: 49, h: 255 },
  'fit-crimson': { src: 'images/labels/fit-crimson.png', w: 49, h: 164 },
  'fit-royal': { src: 'images/labels/fit-royal.png', w: 49, h: 232 },
  'fit-gilded': { src: 'images/labels/fit-gilded.png', w: 49, h: 127 },
  'fit-shadow': { src: 'images/labels/fit-shadow.png', w: 49, h: 248 },
  'fit-hint': { src: 'images/labels/fit-hint.png', w: 49, h: 624 },
  'tab-armor': { src: 'images/labels/tab-armor.png', w: 57, h: 156 },
  'arm-leather': { src: 'images/labels/arm-leather.png', w: 49, h: 261 },
  'arm-chain': { src: 'images/labels/arm-chain.png', w: 49, h: 193 },
  'arm-steel': { src: 'images/labels/arm-steel.png', w: 49, h: 201 },
  'arm-shadow': { src: 'images/labels/arm-shadow.png', w: 49, h: 260 },
  'arm-royal': { src: 'images/labels/arm-royal.png', w: 49, h: 245 },
  'armor-hint': { src: 'images/labels/armor-hint.png', w: 49, h: 964 },
  'armor-none': { src: 'images/labels/armor-none.png', w: 49, h: 193 },
  'armor-owned': { src: 'images/labels/armor-owned.png', w: 44, h: 125 },
  'armor-worn': { src: 'images/labels/armor-worn.png', w: 44, h: 106 },
  'armor-buy': { src: 'images/labels/armor-buy.png', w: 49, h: 147 },
  'armor-poor': { src: 'images/labels/armor-poor.png', w: 49, h: 329 },
  'ow-tailor-1a': { src: 'images/labels/ow-tailor-1a.png', w: 57, h: 954 },
  'ow-tailor-1b': { src: 'images/labels/ow-tailor-1b.png', w: 57, h: 558 }
}

Object.assign(LABELS, WARDROBE_LABELS)
