// AUTO-GENERATED by tools/gen-intro-labels.ps1 -- do not edit by hand.
// Intro story narrator line strips. Importing this module registers them into LABELS.
// One PNG per strip (see lib-labels.ps1 for why not an atlas).
import { LABELS, LabelInfo } from './labels.gen'

export const INTRO_LABELS: Record<string, LabelInfo> = {
  'intro-1a': { src: 'images/labels/intro-1a.png', w: 57, h: 581 },
  'intro-1b': { src: 'images/labels/intro-1b.png', w: 57, h: 651 },
  'intro-2a': { src: 'images/labels/intro-2a.png', w: 57, h: 608 },
  'intro-2b': { src: 'images/labels/intro-2b.png', w: 57, h: 763 },
  'intro-2c': { src: 'images/labels/intro-2c.png', w: 57, h: 643 },
  'intro-3a': { src: 'images/labels/intro-3a.png', w: 57, h: 490 },
  'intro-3b': { src: 'images/labels/intro-3b.png', w: 57, h: 664 },
  'intro-3c': { src: 'images/labels/intro-3c.png', w: 57, h: 894 },
  'intro-4a': { src: 'images/labels/intro-4a.png', w: 57, h: 589 },
  'intro-4b': { src: 'images/labels/intro-4b.png', w: 57, h: 718 },
  'intro-4c': { src: 'images/labels/intro-4c.png', w: 57, h: 713 },
  'intro-4d': { src: 'images/labels/intro-4d.png', w: 57, h: 798 },
  'intro-5a': { src: 'images/labels/intro-5a.png', w: 57, h: 554 },
  'intro-5b': { src: 'images/labels/intro-5b.png', w: 57, h: 637 },
  'intro-5c': { src: 'images/labels/intro-5c.png', w: 57, h: 591 },
  'intro-5d': { src: 'images/labels/intro-5d.png', w: 57, h: 384 },
  'intro-6a': { src: 'images/labels/intro-6a.png', w: 57, h: 955 },
  'intro-6b': { src: 'images/labels/intro-6b.png', w: 57, h: 861 },
  'intro-6c': { src: 'images/labels/intro-6c.png', w: 57, h: 345 },
  'intro-6d': { src: 'images/labels/intro-6d.png', w: 57, h: 660 },
  'intro-w1': { src: 'images/labels/intro-w1.png', w: 57, h: 654 },
  'intro-w2': { src: 'images/labels/intro-w2.png', w: 57, h: 758 },
  'intro-w3': { src: 'images/labels/intro-w3.png', w: 57, h: 573 },
  'intro-f1': { src: 'images/labels/intro-f1.png', w: 57, h: 963 },
  'intro-f2': { src: 'images/labels/intro-f2.png', w: 57, h: 840 },
  'intro-f3': { src: 'images/labels/intro-f3.png', w: 57, h: 936 },
  'intro-f4': { src: 'images/labels/intro-f4.png', w: 57, h: 686 },
  'intro-f5': { src: 'images/labels/intro-f5.png', w: 57, h: 921 },
  'intro-f6': { src: 'images/labels/intro-f6.png', w: 57, h: 596 },
  'intro-f7': { src: 'images/labels/intro-f7.png', w: 57, h: 747 },
  'intro-f8': { src: 'images/labels/intro-f8.png', w: 57, h: 824 },
  'intro-d1': { src: 'images/labels/intro-d1.png', w: 57, h: 702 },
  'intro-d2': { src: 'images/labels/intro-d2.png', w: 57, h: 656 },
  'intro-d3': { src: 'images/labels/intro-d3.png', w: 57, h: 388 }
}

Object.assign(LABELS, INTRO_LABELS)
