// AUTO-GENERATED by tools/gen-feed-labels.ps1 -- do not edit by hand.
// Realm feed, ghost and free-social word strips. Importing this module registers them into LABELS.
// One PNG per strip (see lib-labels.ps1 for why not an atlas).
import { LABELS, LabelInfo } from './labels.gen'

export const FEED_LABELS: Record<string, LabelInfo> = {
  'feed-title': { src: 'images/labels/feed-title.png', w: 57, h: 261 },
  'feed-entered': { src: 'images/labels/feed-entered.png', w: 49, h: 152 },
  'feed-found': { src: 'images/labels/feed-found.png', w: 49, h: 128 },
  'feed-cleared': { src: 'images/labels/feed-cleared.png', w: 49, h: 151 },
  'feed-raid-won': { src: 'images/labels/feed-raid-won.png', w: 49, h: 285 },
  'feed-defeated': { src: 'images/labels/feed-defeated.png', w: 49, h: 169 },
  'feed-felled': { src: 'images/labels/feed-felled.png', w: 49, h: 358 },
  'feed-reached': { src: 'images/labels/feed-reached.png', w: 49, h: 256 },
  'feed-streak': { src: 'images/labels/feed-streak.png', w: 49, h: 429 },
  'feed-beat-ghost': { src: 'images/labels/feed-beat-ghost.png', w: 49, h: 328 },
  'feed-ghost-fell': { src: 'images/labels/feed-ghost-fell.png', w: 49, h: 348 },
  'feed-raided-with': { src: 'images/labels/feed-raided-with.png', w: 49, h: 451 },
  'feed-passed-you': { src: 'images/labels/feed-passed-you.png', w: 49, h: 269 },
  'feed-empty': { src: 'images/labels/feed-empty.png', w: 57, h: 579 },
  'feed-hint': { src: 'images/labels/feed-hint.png', w: 49, h: 560 },
  'feed-yours': { src: 'images/labels/feed-yours.png', w: 49, h: 153 },
  'feed-now': { src: 'images/labels/feed-now.png', w: 44, h: 161 },
  'feed-ago-m': { src: 'images/labels/feed-ago-m.png', w: 44, h: 144 },
  'feed-ago-h': { src: 'images/labels/feed-ago-h.png', w: 44, h: 126 },
  'feed-ago-d': { src: 'images/labels/feed-ago-d.png', w: 44, h: 160 },
  ghost: { src: 'images/labels/ghost.png', w: 49, h: 122 },
  'fight-a-ghost': { src: 'images/labels/fight-a-ghost.png', w: 66, h: 345 },
  'ghost-hint': { src: 'images/labels/ghost-hint.png', w: 49, h: 929 },
  'ghost-allies': { src: 'images/labels/ghost-allies.png', w: 49, h: 896 },
  'ghost-called': { src: 'images/labels/ghost-called.png', w: 57, h: 587 },
  'raid-free': { src: 'images/labels/raid-free.png', w: 57, h: 302 },
  'spoils-left': { src: 'images/labels/spoils-left.png', w: 49, h: 419 },
  'spoils-spent': { src: 'images/labels/spoils-spent.png', w: 49, h: 704 },
  'duel-free': { src: 'images/labels/duel-free.png', w: 57, h: 467 },
  'set-appearance': { src: 'images/labels/set-appearance.png', w: 57, h: 258 },
  'look-skin': { src: 'images/labels/look-skin.png', w: 49, h: 86 },
  'look-hair': { src: 'images/labels/look-hair.png', w: 49, h: 89 },
  'look-short': { src: 'images/labels/look-short.png', w: 49, h: 204 },
  'look-long': { src: 'images/labels/look-long.png', w: 49, h: 189 },
  'look-avatar': { src: 'images/labels/look-avatar.png', w: 49, h: 526 },
  'look-hint': { src: 'images/labels/look-hint.png', w: 49, h: 843 }
}

Object.assign(LABELS, FEED_LABELS)
