// AUTO-GENERATED by tools/gen-boss-labels.ps1 -- do not edit by hand.
// World Boss lair word strips. Importing this module registers them into LABELS.
// One PNG per strip (see lib-labels.ps1 for why not an atlas).
import { LABELS, LabelInfo } from './labels.gen'

export const BOSS_LABELS: Record<string, LabelInfo> = {
  'world-boss': { src: 'images/labels/world-boss.png', w: 86, h: 322 },
  'boss-title': { src: 'images/labels/boss-title.png', w: 75, h: 341 },
  'boss-hint': { src: 'images/labels/boss-hint.png', w: 49, h: 568 },
  'boss-tab-lair': { src: 'images/labels/boss-tab-lair.png', w: 62, h: 189 },
  'boss-tab-board': { src: 'images/labels/boss-tab-board.png', w: 62, h: 346 },
  'world-hp': { src: 'images/labels/world-hp.png', w: 49, h: 184 },
  tier: { src: 'images/labels/tier.png', w: 49, h: 78 },
  'boss-kills': { src: 'images/labels/boss-kills.png', w: 44, h: 297 },
  'boss-ends-in': { src: 'images/labels/boss-ends-in.png', w: 49, h: 270 },
  'boss-fighting': { src: 'images/labels/boss-fighting.png', w: 44, h: 258 },
  attack: { src: 'images/labels/attack.png', w: 66, h: 181 },
  'attacks-left': { src: 'images/labels/attacks-left.png', w: 49, h: 346 },
  'your-best': { src: 'images/labels/your-best.png', w: 49, h: 244 },
  'boss-minute': { src: 'images/labels/boss-minute.png', w: 49, h: 535 },
  'no-attacks': { src: 'images/labels/no-attacks.png', w: 49, h: 610 },
  'boss-busy': { src: 'images/labels/boss-busy.png', w: 49, h: 515 },
  'boss-party': { src: 'images/labels/boss-party.png', w: 49, h: 484 },
  'best-hit': { src: 'images/labels/best-hit.png', w: 57, h: 172 },
  dmg: { src: 'images/labels/dmg.png', w: 49, h: 91 },
  'boss-empty': { src: 'images/labels/boss-empty.png', w: 57, h: 525 },
  'boss-rewards': { src: 'images/labels/boss-rewards.png', w: 44, h: 848 },
  'reward-1': { src: 'images/labels/reward-1.png', w: 44, h: 464 },
  'reward-top3': { src: 'images/labels/reward-top3.png', w: 44, h: 511 },
  'reward-top10': { src: 'images/labels/reward-top10.png', w: 44, h: 486 },
  'reward-all': { src: 'images/labels/reward-all.png', w: 44, h: 581 },
  'time-left': { src: 'images/labels/time-left.png', w: 49, h: 165 },
  dealt: { src: 'images/labels/dealt.png', w: 57, h: 305 },
  'party-fell': { src: 'images/labels/party-fell.png', w: 57, h: 335 },
  'new-best': { src: 'images/labels/new-best.png', w: 49, h: 170 },
  'boss-felled': { src: 'images/labels/boss-felled.png', w: 66, h: 287 },
  'boss-rises': { src: 'images/labels/boss-rises.png', w: 49, h: 474 },
  'boss-again': { src: 'images/labels/boss-again.png', w: 57, h: 289 },
  'boss-spoils': { src: 'images/labels/boss-spoils.png', w: 66, h: 458 },
  'feed-boss-hit': { src: 'images/labels/feed-boss-hit.png', w: 49, h: 422 },
  'feed-boss-fell': { src: 'images/labels/feed-boss-fell.png', w: 49, h: 406 }
}

Object.assign(LABELS, BOSS_LABELS)
