// AUTO-GENERATED by tools/gen-story-labels.ps1 -- do not edit by hand.
// Road-story / final-battle / epilogue narrator strips. Importing this module registers them into LABELS.
// One PNG per strip (see lib-labels.ps1 for why not an atlas).
import { LABELS, LabelInfo } from './labels.gen'

export const STORY_LABELS: Record<string, LabelInfo> = {
  'story-q1-1a': { src: 'images/labels/story-q1-1a.png', w: 57, h: 846 },
  'story-q1-1b': { src: 'images/labels/story-q1-1b.png', w: 57, h: 754 },
  'story-q1-1c': { src: 'images/labels/story-q1-1c.png', w: 57, h: 915 },
  'story-q1-2a': { src: 'images/labels/story-q1-2a.png', w: 57, h: 836 },
  'story-q1-2b': { src: 'images/labels/story-q1-2b.png', w: 57, h: 711 },
  'story-q1-2c': { src: 'images/labels/story-q1-2c.png', w: 57, h: 619 },
  'story-q3-1a': { src: 'images/labels/story-q3-1a.png', w: 57, h: 857 },
  'story-q3-1b': { src: 'images/labels/story-q3-1b.png', w: 57, h: 901 },
  'story-q3-1c': { src: 'images/labels/story-q3-1c.png', w: 57, h: 803 },
  'story-q3-2a': { src: 'images/labels/story-q3-2a.png', w: 57, h: 942 },
  'story-q3-2b': { src: 'images/labels/story-q3-2b.png', w: 57, h: 786 },
  'story-q3-2c': { src: 'images/labels/story-q3-2c.png', w: 57, h: 731 },
  'story-q4-1a': { src: 'images/labels/story-q4-1a.png', w: 57, h: 870 },
  'story-q4-1b': { src: 'images/labels/story-q4-1b.png', w: 57, h: 734 },
  'story-q4-1c': { src: 'images/labels/story-q4-1c.png', w: 57, h: 688 },
  'story-q4-2a': { src: 'images/labels/story-q4-2a.png', w: 57, h: 864 },
  'story-q4-2b': { src: 'images/labels/story-q4-2b.png', w: 57, h: 839 },
  'story-q4-2c': { src: 'images/labels/story-q4-2c.png', w: 57, h: 725 },
  'story-q6-1a': { src: 'images/labels/story-q6-1a.png', w: 57, h: 853 },
  'story-q6-1b': { src: 'images/labels/story-q6-1b.png', w: 57, h: 614 },
  'story-q6-1c': { src: 'images/labels/story-q6-1c.png', w: 57, h: 808 },
  'story-q6-2a': { src: 'images/labels/story-q6-2a.png', w: 57, h: 771 },
  'story-q6-2b': { src: 'images/labels/story-q6-2b.png', w: 57, h: 517 },
  'story-q6-2c': { src: 'images/labels/story-q6-2c.png', w: 57, h: 604 },
  'story-final-1a': { src: 'images/labels/story-final-1a.png', w: 57, h: 723 },
  'story-final-1b': { src: 'images/labels/story-final-1b.png', w: 57, h: 848 },
  'story-final-1c': { src: 'images/labels/story-final-1c.png', w: 57, h: 704 },
  'story-final-2a': { src: 'images/labels/story-final-2a.png', w: 57, h: 854 },
  'story-final-2b': { src: 'images/labels/story-final-2b.png', w: 57, h: 659 },
  'story-final-2c': { src: 'images/labels/story-final-2c.png', w: 57, h: 685 },
  'story-epilogue-1a': { src: 'images/labels/story-epilogue-1a.png', w: 57, h: 795 },
  'story-epilogue-1b': { src: 'images/labels/story-epilogue-1b.png', w: 57, h: 751 },
  'story-epilogue-1c': { src: 'images/labels/story-epilogue-1c.png', w: 57, h: 776 },
  'story-epilogue-2a': { src: 'images/labels/story-epilogue-2a.png', w: 57, h: 720 },
  'story-epilogue-2b': { src: 'images/labels/story-epilogue-2b.png', w: 57, h: 535 },
  'story-epilogue-2c': { src: 'images/labels/story-epilogue-2c.png', w: 57, h: 606 },
  'story-final-name': { src: 'images/labels/story-final-name.png', w: 57, h: 452 }
}

Object.assign(LABELS, STORY_LABELS)
