// AUTO-GENERATED by tools/gen-credits-labels.ps1 -- do not edit by hand.
// Credits-roll line strips. Importing this module registers them into LABELS.
// One PNG per strip (see lib-labels.ps1 for why not an atlas).
import { LABELS, LabelInfo } from './labels.gen'

export const CREDITS_LABELS: Record<string, LabelInfo> = {
  'credits-created': { src: 'images/labels/credits-created.png', w: 57, h: 236 },
  'credits-matt': { src: 'images/labels/credits-matt.png', w: 57, h: 120 },
  'credits-role': { src: 'images/labels/credits-role.png', w: 57, h: 680 },
  'credits-voice': { src: 'images/labels/credits-voice.png', w: 57, h: 343 },
  'credits-eleven': { src: 'images/labels/credits-eleven.png', w: 57, h: 240 },
  'credits-art': { src: 'images/labels/credits-art.png', w: 57, h: 202 },
  'credits-art2': { src: 'images/labels/credits-art2.png', w: 57, h: 632 },
  'credits-built': { src: 'images/labels/credits-built.png', w: 57, h: 226 },
  'credits-sdk': { src: 'images/labels/credits-sdk.png', w: 57, h: 419 },
  'credits-for': { src: 'images/labels/credits-for.png', w: 57, h: 202 },
  'credits-regenesis': { src: 'images/labels/credits-regenesis.png', w: 57, h: 312 },
  'credits-buildathon': { src: 'images/labels/credits-buildathon.png', w: 57, h: 507 },
  'credits-starring': { src: 'images/labels/credits-starring.png', w: 57, h: 200 },
  'credits-warlords': { src: 'images/labels/credits-warlords.png', w: 57, h: 419 },
  'credits-tale': { src: 'images/labels/credits-tale.png', w: 57, h: 391 },
  'credits-thanks': { src: 'images/labels/credits-thanks.png', w: 57, h: 419 },
  'credits-fire': { src: 'images/labels/credits-fire.png', w: 57, h: 744 }
}

Object.assign(LABELS, CREDITS_LABELS)
