// AUTO-GENERATED by tools/gen-level-labels.ps1 -- do not edit by hand.
// Account-level word strips (HUD badge, level-up ceremony, level card). Importing this module registers them into LABELS.
// One PNG per strip (see lib-labels.ps1 for why not an atlas).
import { LABELS, LabelInfo } from './labels.gen'

export const LEVEL_LABELS: Record<string, LabelInfo> = {
  lv: { src: 'images/labels/lv.png', w: 57, h: 59 },
  'level-up': { src: 'images/labels/level-up.png', w: 66, h: 207 },
  'acct-level': { src: 'images/labels/acct-level.png', w: 57, h: 119 },
  'max-level': { src: 'images/labels/max-level.png', w: 49, h: 183 },
  'xp-to-next': { src: 'images/labels/xp-to-next.png', w: 49, h: 292 },
  'energy-refilled': { src: 'images/labels/energy-refilled.png', w: 49, h: 281 },
  'max-energy': { src: 'images/labels/max-energy.png', w: 49, h: 218 },
  'new-hero-joins': { src: 'images/labels/new-hero-joins.png', w: 49, h: 392 },
  'free-hero-at': { src: 'images/labels/free-hero-at.png', w: 49, h: 327 },
  'level-hint': { src: 'images/labels/level-hint.png', w: 49, h: 496 },
  'level-rewards': { src: 'images/labels/level-rewards.png', w: 49, h: 688 }
}

Object.assign(LABELS, LEVEL_LABELS)
