// AUTO-GENERATED by tools/gen-hall-labels.ps1 -- do not edit by hand.
// Hall of Heroes (leaderboard) word strips. Importing this module registers them into LABELS.
// One PNG per strip (see lib-labels.ps1 for why not an atlas).
import { LABELS, LabelInfo } from './labels.gen'

export const HALL_LABELS: Record<string, LabelInfo> = {
  'hall-title': { src: 'images/labels/hall-title.png', w: 75, h: 424 },
  'board-level': { src: 'images/labels/board-level.png', w: 57, h: 119 },
  'board-roads': { src: 'images/labels/board-roads.png', w: 57, h: 145 },
  'board-raids': { src: 'images/labels/board-raids.png', w: 57, h: 126 },
  'board-duels': { src: 'images/labels/board-duels.png', w: 57, h: 132 },
  'your-rank': { src: 'images/labels/your-rank.png', w: 49, h: 198 },
  'rank-hash': { src: 'images/labels/rank-hash.png', w: 66, h: 45 },
  unranked: { src: 'images/labels/unranked.png', w: 49, h: 191 },
  'hall-empty': { src: 'images/labels/hall-empty.png', w: 57, h: 601 },
  'hall-first': { src: 'images/labels/hall-first.png', w: 49, h: 210 },
  'hall-hint': { src: 'images/labels/hall-hint.png', w: 49, h: 605 }
}

Object.assign(LABELS, HALL_LABELS)
