"""Build the face atlas: every hero's idle poster (cell 0 of its combat
sheet) at 128px, packed 8x8 into one 1024x1024 sheet.

Small faces (home party, bench tiles, seat plates, feed lines, results) used
to sample cell 0 of each hero's 1024x1024 combat sheet, so a screen showing
N heroes kept N four-megabyte textures resident - and the home screen warmed
the whole collection. One atlas replaces all of them; the combat sheets now
bind only for the fight.

Reads the sheet table out of src/ui/fx/sheets.ts (single source of truth),
writes images/chars/faces-a.png and src/ui/faces.gen.ts. Re-run after adding
a hero, then `python tools/quantize-images.py images/chars/faces-a.png`.
"""

import os
import re
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHEETS_TS = os.path.join(ROOT, "src", "ui", "fx", "sheets.ts")
OUT_PNG = os.path.join(ROOT, "images", "chars", "faces-a.png")
OUT_TS = os.path.join(ROOT, "src", "ui", "faces.gen.ts")

ATLAS = 1024
GRID = 8
CELL = ATLAS // GRID  # 128
# The combat sheets: 4x4 grid; cell 0 (top-left) is the idle poster.
SHEET_GRID = 4


def read_sheets() -> list:
    with open(SHEETS_TS, encoding="utf-8") as f:
        src = f.read()
    m = re.search(r"const SHEETS: Record<string, string> = \{(.*?)\n\}", src, re.S)
    if not m:
        sys.exit("SHEETS table not found in sheets.ts")
    pairs = re.findall(r"^\s*'?([a-z0-9-]+)'?:\s*'([^']+)'", m.group(1), re.M)
    if not pairs:
        sys.exit("no sheet entries parsed")
    return pairs


def main() -> int:
    sheets = read_sheets()
    if len(sheets) > GRID * GRID:
        sys.exit(f"{len(sheets)} heroes but the atlas holds {GRID * GRID}; grow GRID")
    atlas = Image.new("RGBA", (ATLAS, ATLAS), (0, 0, 0, 0))
    slots = []
    for slot, (hero_id, rel) in enumerate(sheets):
        path = os.path.join(ROOT, rel)
        sheet = Image.open(path).convert("RGBA")
        cw = sheet.size[0] // SHEET_GRID
        ch = sheet.size[1] // SHEET_GRID
        face = sheet.crop((0, 0, cw, ch)).resize((CELL, CELL), Image.LANCZOS)
        x = (slot % GRID) * CELL
        y = (slot // GRID) * CELL
        atlas.paste(face, (x, y))
        slots.append((hero_id, slot))
    atlas.save(OUT_PNG, optimize=True)

    lines = [
        "// Generated by tools/build-face-atlas.py - do not edit.",
        "// Slot of each hero's idle face in images/chars/faces-a.png (8x8 grid of 128px).",
        "",
        f"export const FACE_ATLAS_SRC = 'images/chars/faces-a.png'",
        f"export const FACE_GRID = {GRID}",
        "",
        "export const FACE_SLOT: Record<string, number> = {",
    ]
    for hero_id, slot in slots:
        key = hero_id if re.fullmatch(r"[a-z][a-z0-9]*", hero_id) else f"'{hero_id}'"
        lines.append(f"  {key}: {slot},")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("}")
    lines.append("")
    with open(OUT_TS, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"{len(slots)} faces -> {os.path.relpath(OUT_PNG, ROOT)} ({os.path.getsize(OUT_PNG) // 1024} KB), {os.path.relpath(OUT_TS, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
