# Renders the road-story / final-battle / epilogue narrator line strips in the
# same style as the other label generators: white all-caps Segoe UI on a
# transparent background, rotated 90 CCW so glyphs read bottom-to-top in
# landscape and upright in the portrait grip (matches gen-intro-labels.ps1).
#
# Usage:  powershell -NoProfile -ExecutionPolicy Bypass -File tools/gen-story-labels.ps1
# Emits:  images/labels/story-*.png  +  src/ui/labels.story.gen.ts

Add-Type -AssemblyName System.Drawing

$root = Split-Path $PSScriptRoot -Parent
$outDir = Join-Path $root 'images\labels'
$tsPath = Join-Path $root 'src\ui\labels.story.gen.ts'

# Supersampled 2x for high-DPR phones; display sizes are stage units and derive
# height from the aspect ratio, so layout is unchanged - strips just stay crisp.
$scale = 2
$fontPx = 26 * $scale
$font = New-Object System.Drawing.Font('Segoe UI', $fontPx, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)

$lines = [ordered]@{
  # --- q1 The Moor Gate ------------------------------------------------------
  'story-q1-1a' = 'THE FIRST ROAD RUNS THROUGH THE MOOR,'
  'story-q1-1b' = 'WHERE THE OGRE HAS TAKEN THE GATE.'
  'story-q1-1c' = 'HIS HOUNDS AND WIGHTS HUNT THE CROSSING.'
  'story-q1-2a' = 'NO GRAIN, NO WORD, NO HELP PASSES HIM.'
  'story-q1-2b' = 'ANTROM STARVES BEHIND ITS WALLS.'
  'story-q1-2c' = 'BREAK THE GATE. FELL THE OGRE.'
  # --- q3 Crow Road ----------------------------------------------------------
  'story-q3-1a' = 'THE CROW ROAD CARRIED OUR MESSENGERS.'
  'story-q3-1b' = 'NOW THE THORN QUEEN''S BRIARS STRANGLE IT,'
  'story-q3-1c' = 'AND HER CROWS PICK THE SILENCE CLEAN.'
  'story-q3-2a' = 'NO WARNING CAN REACH THE OTHER KINGDOMS.'
  'story-q3-2b' = 'SHE WILL BURY THEM BLIND, ONE BY ONE.'
  'story-q3-2c' = 'CUT THE BRIAR. TAKE BACK OUR VOICE.'
  # --- q4 The Veiled Well ----------------------------------------------------
  'story-q4-1a' = 'THE WELL BENEATH THE VEIL FED OUR FLAME -'
  'story-q4-1b' = 'EVERY OATH DRAWN FROM ITS WATER.'
  'story-q4-1c' = 'THE CRIMSON ABBOT BLEEDS IT DRY.'
  'story-q4-2a' = 'WITH EVERY DROP HE DRINKS, OUR FIRE DIMS.'
  'story-q4-2b' = 'WHEN THE WELL RUNS RED, THE FLAME DIES.'
  'story-q4-2c' = 'SPILL THE ABBOT BEFORE HE SPILLS US.'
  # --- q6 The Oath Hall ------------------------------------------------------
  'story-q6-1a' = 'THE OLD OATH HALL, WHERE HEROES SWORE,'
  'story-q6-1b' = 'NOW SEATS A KING OF CINDERS.'
  'story-q6-1c' = 'THE ASHEN REGENT TURNS OATHS TO ASH.'
  'story-q6-2a' = 'EVERY BROKEN OATH SWELLS HIS RANKS.'
  'story-q6-2b' = 'HIS ARMY IS NEARLY RISEN.'
  'story-q6-2c' = 'UNSEAT HIM, OR KNEEL TO ASH.'
  # --- final battle prelude: the Gates of Antrom -----------------------------
  'story-final-1a' = 'YOU BROKE THEM EACH ALONE, HERO.'
  'story-final-1b' = 'SO THE DEMON KING PLAYED HIS LAST CARD:'
  'story-final-1c' = 'ALL FOUR, RISEN, MARCHING AS ONE.'
  'story-final-2a' = 'THERE ARE NO MORE ROADS. NO MORE TIME.'
  'story-final-2b' = 'THEY COME FOR THE FLAME ITSELF.'
  'story-final-2c' = 'STAND AT THE GATE. END THIS WAR.'
  # --- victory epilogue ------------------------------------------------------
  'story-epilogue-1a' = 'THE WARLORDS LIE BROKEN AT OUR GATE.'
  'story-epilogue-1b' = 'THE DEMON KING''S REACH ENDS HERE -'
  'story-epilogue-1c' = 'HE DARES NOT FACE WHAT FELLED THEM.'
  'story-epilogue-2a' = 'THE FLAME BURNS TALLER THAN EVER,'
  'story-epilogue-2b' = 'FED BY THE OATH YOU KEPT.'
  'story-epilogue-2c' = 'ANTROM REMEMBERS ITS HERO.'
  # --- map row name plate ----------------------------------------------------
  'story-final-name' = 'THE GATES OF ANTROM'
}

$entries = New-Object System.Collections.Generic.List[string]

foreach ($kv in $lines.GetEnumerator()) {
  $key = $kv.Key
  $text = $kv.Value

  $probe = New-Object System.Drawing.Bitmap(8, 8)
  $pg = [System.Drawing.Graphics]::FromImage($probe)
  $pg.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAlias
  $size = $pg.MeasureString($text, $font)
  $pg.Dispose(); $probe.Dispose()

  $w = [int][Math]::Ceiling($size.Width) + 2
  $h = [int][Math]::Ceiling($size.Height)

  $bmp = New-Object System.Drawing.Bitmap($w, $h, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
  $g = [System.Drawing.Graphics]::FromImage($bmp)
  $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAlias
  $g.DrawString($text, $font, [System.Drawing.Brushes]::White, 1, 0)
  $g.Dispose()

  # Same orientation as every other label: 90 CCW, reads bottom-to-top in landscape.
  $bmp.RotateFlip([System.Drawing.RotateFlipType]::Rotate270FlipNone)
  $file = Join-Path $outDir "$key.png"
  $bmp.Save($file, [System.Drawing.Imaging.ImageFormat]::Png)
  $entries.Add("  '$key': { src: 'images/labels/$key.png', w: $($bmp.Width), h: $($bmp.Height) },")
  $bmp.Dispose()
}

$font.Dispose()

$body = ($entries -join "`n").TrimEnd(',')
$ts = @"
// AUTO-GENERATED by tools/gen-story-labels.ps1 -- do not edit by hand.
// Road-story / final-battle / epilogue narrator strips, pre-rotated like
// every other label. Importing this module registers them into LABELS.
import { LABELS, LabelInfo } from './labels.gen'

export const STORY_LABELS: Record<string, LabelInfo> = {
$body
}

Object.assign(LABELS, STORY_LABELS)
"@

Set-Content -Path $tsPath -Value $ts -Encoding UTF8
Write-Host "Wrote $($lines.Count) strips to images/labels and $tsPath"
