# Renders the credits-roll line strips in the same style as the other label
# generators: white all-caps Segoe UI on a transparent background, rotated 90
# CCW so glyphs read bottom-to-top in landscape and upright in the portrait
# grip (same convention as gen-tut-labels.ps1).
#
# Usage:  powershell -NoProfile -ExecutionPolicy Bypass -File tools/gen-credits-labels.ps1
# Emits:  images/labels/credits-*.png  +  src/ui/labels.credits.gen.ts

Add-Type -AssemblyName System.Drawing

$root = Split-Path $PSScriptRoot -Parent
$outDir = Join-Path $root 'images\labels'
$tsPath = Join-Path $root 'src\ui\labels.credits.gen.ts'

# 26px Segoe UI measures ~34px tall with ascent/descent, matching the fire-line strips.
# Supersampled 2x for high-DPR phones; display sizes are stage units and derive
# height from the aspect ratio, so layout is unchanged - strips just stay crisp.
$scale = 2
$fontPx = 26 * $scale
$font = New-Object System.Drawing.Font('Segoe UI', $fontPx, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)

$lines = [ordered]@{
  'credits-created'    = 'CREATED BY'
  'credits-matt'       = 'MATT'
  'credits-role'       = 'STORY, ART DIRECTION AND DESIGN'
  'credits-voice'      = 'NARRATOR VOICE'
  'credits-eleven'     = 'ELEVENLABS'
  'credits-art'        = 'ARTWORK'
  'credits-art2'       = 'GENERATED AND HAND FINISHED'
  'credits-built'      = 'BUILT WITH'
  'credits-sdk'        = 'DECENTRALAND SDK7'
  'credits-for'        = 'BUILT FOR'
  'credits-regenesis'  = 'REGENESIS LABS'
  'credits-buildathon' = 'FRIENDZONE BUILDATHON'
  'credits-starring'   = 'STARRING'
  'credits-warlords'   = 'THE FOUR WARLORDS'
  'credits-tale'       = 'A GENESIS CITY TALE'
  'credits-thanks'     = 'THANKS FOR PLAYING'
  'credits-fire'       = 'ANTROM STANDS - THE FIRE BURNS ON'
}

$entries = New-Object System.Collections.Generic.List[string]

foreach ($kv in $lines.GetEnumerator()) {
  $key = $kv.Key
  $text = $kv.Value

  $probe = New-Object System.Drawing.Bitmap(8, 8)
  $pg = [System.Drawing.Graphics]::FromImage($probe)
  $pg.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAlias
  $size = $pg.MeasureString($text, $font)
  $pg.Dispose(); $probe.Dispose()

  $w = [int][Math]::Ceiling($size.Width) + 2
  $h = [int][Math]::Ceiling($size.Height)

  $bmp = New-Object System.Drawing.Bitmap($w, $h, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
  $g = [System.Drawing.Graphics]::FromImage($bmp)
  $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAlias
  $g.DrawString($text, $font, [System.Drawing.Brushes]::White, 1, 0)
  $g.Dispose()

  # Same orientation as every other label: 90 CCW, reads bottom-to-top in landscape.
  $bmp.RotateFlip([System.Drawing.RotateFlipType]::Rotate270FlipNone)
  $file = Join-Path $outDir "$key.png"
  $bmp.Save($file, [System.Drawing.Imaging.ImageFormat]::Png)
  $entries.Add("  '$key': { src: 'images/labels/$key.png', w: $($bmp.Width), h: $($bmp.Height) },")
  $bmp.Dispose()
}

$font.Dispose()

$body = ($entries -join "`n").TrimEnd(',')
$ts = @"
// AUTO-GENERATED by tools/gen-credits-labels.ps1 -- do not edit by hand.
// Credits-roll line strips, pre-rotated like every other label. Importing
// this module registers them into the shared LABELS map.
import { LABELS, LabelInfo } from './labels.gen'

export const CREDITS_LABELS: Record<string, LabelInfo> = {
$body
}

Object.assign(LABELS, CREDITS_LABELS)
"@

Set-Content -Path $tsPath -Value $ts -Encoding UTF8
Write-Host "Wrote $($lines.Count) strips to images/labels and $tsPath"
