# Renders the friendzone duel word strips in the same style as the other
# labels: white all-caps Segoe UI on a transparent background, rotated 90 CCW
# so glyphs read bottom-to-top in landscape and upright in the portrait grip.
#
# Usage:  powershell -NoProfile -ExecutionPolicy Bypass -File tools/gen-duel-labels.ps1
# Emits:  images/labels/<key>.png  +  src/ui/labels.duel.gen.ts

Add-Type -AssemblyName System.Drawing

$root = Split-Path $PSScriptRoot -Parent
$outDir = Join-Path $root 'images\labels'
$tsPath = Join-Path $root 'src\ui\labels.duel.gen.ts'

# size 30 = word labels (matches shop/trade/rift strips), 26 = hint lines.
$lines = [ordered]@{
  'raids'            = @{ text = 'RAIDS'; size = 30 }
  'duels'            = @{ text = 'DUELS'; size = 30 }
  'victor'           = @{ text = 'VICTOR'; size = 30 }
  'duel-1v1'         = @{ text = '1 VS 1'; size = 30 }
  'duel-4v4'         = @{ text = '4 VS 4'; size = 30 }
  'leaderboard'      = @{ text = 'LEADERBOARD'; size = 26 }
  'wins'             = @{ text = 'WINS'; size = 22 }
  'player-vs-player' = @{ text = 'PLAYER VS PLAYER'; size = 26 }
  'awaiting-foe'     = @{ text = 'AWAITING A CHALLENGER'; size = 26 }
  'duel-cost'        = @{ text = 'THE DUEL COSTS 2 ENERGY'; size = 26 }
  'duel-cost4'       = @{ text = 'THE DUEL COSTS 4 ENERGY'; size = 26 }
  'need-four'        = @{ text = 'YOU NEED FOUR HEROES IN YOUR PARTY'; size = 26 }
  'join-duel'        = @{ text = 'JOIN THE DUEL'; size = 30 }
  'join-raid'        = @{ text = 'JOIN THE RAID'; size = 30 }
  # step-by-step lobby hints (state-driven, one visible at a time)
  'pick-your-champion' = @{ text = 'TAP A HERO TO PICK YOUR CHAMPION'; size = 26 }
  'tap-join-party'     = @{ text = 'TAP JOIN TO FIELD YOUR PARTY'; size = 26 }
  'tap-enter-ready'    = @{ text = 'TAP ENTER WHEN READY'; size = 26 }
  'foe-not-ready'      = @{ text = 'WAITING ON YOUR FOE'; size = 26 }
}

$entries = New-Object System.Collections.Generic.List[string]

# Supersampled 2x for high-DPR phones; display sizes are stage units and derive
# height from the aspect ratio, so layout is unchanged - strips just stay crisp.
$scale = 2

foreach ($kv in $lines.GetEnumerator()) {
  $key = $kv.Key
  $text = $kv.Value.text
  $fontPx = $kv.Value.size * $scale
  $font = New-Object System.Drawing.Font('Segoe UI', $fontPx, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)

  $probe = New-Object System.Drawing.Bitmap(8, 8)
  $pg = [System.Drawing.Graphics]::FromImage($probe)
  $pg.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAlias
  $size = $pg.MeasureString($text, $font)
  $pg.Dispose(); $probe.Dispose()

  $w = [int][Math]::Ceiling($size.Width) + 2
  $h = [int][Math]::Ceiling($size.Height)

  $bmp = New-Object System.Drawing.Bitmap($w, $h, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
  $g = [System.Drawing.Graphics]::FromImage($bmp)
  $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAlias
  $g.DrawString($text, $font, [System.Drawing.Brushes]::White, 1, 0)
  $g.Dispose()

  # Same orientation as every other label: 90 CCW, reads bottom-to-top in landscape.
  $bmp.RotateFlip([System.Drawing.RotateFlipType]::Rotate270FlipNone)
  $file = Join-Path $outDir "$key.png"
  $bmp.Save($file, [System.Drawing.Imaging.ImageFormat]::Png)
  $entries.Add("  '$key': { src: 'images/labels/$key.png', w: $($bmp.Width), h: $($bmp.Height) },")
  $bmp.Dispose()
  $font.Dispose()
}

$body = ($entries -join "`n").TrimEnd(',')
$ts = @"
// AUTO-GENERATED by tools/gen-duel-labels.ps1 -- do not edit by hand.
// Friendzone duel word strips, pre-rotated like every other label. Importing
// this module registers them into the shared LABELS map.
import { LABELS, LabelInfo } from './labels.gen'

export const DUEL_LABELS: Record<string, LabelInfo> = {
$body
}

Object.assign(LABELS, DUEL_LABELS)
"@

Set-Content -Path $tsPath -Value $ts -Encoding UTF8
Write-Host "Wrote $($lines.Count) strips to images/labels and $tsPath"
