# Renders the tutorial dialog line strips in the same style as the original
# gen-labels.ps1 output (which was never committed): white all-caps Segoe UI on
# a transparent background, rotated 90 CCW so glyphs read bottom-to-top in
# landscape and upright in the portrait grip (matches images/labels/fire-line*.png,
# ~34px strip thickness).
#
# Usage:  powershell -NoProfile -ExecutionPolicy Bypass -File tools/gen-tut-labels.ps1
# Emits:  images/labels/tut-*.png  +  src/ui/labels.tut.gen.ts

Add-Type -AssemblyName System.Drawing

$root = Split-Path $PSScriptRoot -Parent
$outDir = Join-Path $root 'images\labels'
$tsPath = Join-Path $root 'src\ui\labels.tut.gen.ts'

# 26px Segoe UI measures ~34px tall with ascent/descent, matching the fire-line strips.
$font = New-Object System.Drawing.Font('Segoe UI', 26, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)

$lines = [ordered]@{
  # party
  'tut-party-1a'      = 'TAP A BENCH HERO'
  'tut-party-1b'      = 'TO SEAT THEM IN YOUR PARTY.'
  'tut-party-1c'      = 'YOUR FOUR SEATS FIGHT THE ROADS.'
  'tut-party-2a'      = 'TAP A SEAT, THEN A HERO, TO SWAP.'
  'tut-party-2b'      = 'TAP THE SAME SEAT TWICE'
  'tut-party-2c'      = 'TO SEND THEM BACK TO THE BENCH.'
  # map
  'tut-map-1a'        = 'TAP A ROAD TO SEE ITS FLOORS.'
  'tut-map-1b'        = 'EACH ROAD CLIMBS TO A BOSS,'
  'tut-map-1c'        = 'AND BOSSES DROP HEROES.'
  'tut-map-2a'        = 'EACH FIGHT COSTS 1 ENERGY.'
  'tut-map-2b'        = 'BEAT THE BOSS TO RAISE ITS STAR.'
  'tut-map-2c'        = 'FIVE STARS MASTERS THE ROAD.'
  # settings
  'tut-settings-1a'   = 'TAP SOUND OR MUSIC'
  'tut-settings-1b'   = 'TO TURN THEM ON OR OFF.'
  'tut-settings-1c'   = 'RESTART WIPES YOUR ACCOUNT - IT ASKS FIRST.'
  # events
  'tut-events-1a'     = 'THE WHOLE REALM FILLS ONE GOAL BAR.'
  'tut-events-1b'     = 'WHEN IT FILLS, ALL WHO HELPED'
  'tut-events-1c'     = 'SHARE THE REWARD.'
  'tut-events-2a'     = 'TAP SEND TO GIFT A PLAYER.'
  'tut-events-2b'     = 'ONE GIFT A DAY - AND THE SENDER'
  'tut-events-2c'     = 'IS BLESSED WITH COINS TOO.'
  # fuse
  'tut-fuse-1a'       = 'TAP A HERO FACE, THEN A STAR RANK'
  'tut-fuse-1b'       = 'WHERE YOU OWN TWO COPIES.'
  'tut-fuse-1c'       = 'BOTH SEATS FILL ON THEIR OWN.'
  'tut-fuse-2a'       = 'TAP ACCEPT TO FUSE THE PAIR'
  'tut-fuse-2b'       = 'INTO ONE HERO, ONE STAR HIGHER.'
  'tut-fuse-2c'       = 'SAME HERO, SAME STARS, TWO COPIES.'
  # shop
  'tut-shop-1a'       = 'TAP A PACK TO BUY IT WITH COINS,'
  'tut-shop-1b'       = 'THEN TAP ACCEPT TO OPEN THE CHEST.'
  'tut-shop-1c'       = 'EVERY CHEST HOLDS A HERO CARD.'
  'tut-shop-2a'       = 'BIGGER PACKS COST MORE COINS'
  'tut-shop-2b'       = 'AND DROP RARER HEROES.'
  'tut-shop-2c'       = 'EARN COINS ON THE ROADS.'
  # trade
  'tut-trade-1a'      = 'TAP A TRAVELER TO INVITE THEM'
  'tut-trade-1b'      = 'TO THE TRADING TABLE.'
  'tut-trade-1c'      = 'THEY MUST ACCEPT TO SIT.'
  'tut-trade-2a'      = 'TAP A CARD TO OFFER IT,'
  'tut-trade-2b'      = 'THEN TAP YOUR LOCK.'
  'tut-trade-2c'      = 'WHEN BOTH SIDES LOCK, CARDS SWAP.'
  # friendzone
  'tut-friendzone-1a' = 'TAP A HERO TO TAKE A SEAT.'
  'tut-friendzone-1b' = 'THE RAID COSTS 5 ENERGY'
  'tut-friendzone-1c' = 'WHEN THE FIGHT BEGINS.'
  'tut-friendzone-2a' = 'TAP ENTER WHEN YOU ARE READY.'
  'tut-friendzone-2b' = 'WHEN ALL SEATED ARE READY, IT BEGINS.'
  'tut-friendzone-2c' = 'EVERY RAIDER SHARES THE SPOILS.'
  # shared
  'tut-continue'      = 'TAP TO CONTINUE'
}

$entries = New-Object System.Collections.Generic.List[string]

foreach ($kv in $lines.GetEnumerator()) {
  $key = $kv.Key
  $text = $kv.Value

  $probe = New-Object System.Drawing.Bitmap(8, 8)
  $pg = [System.Drawing.Graphics]::FromImage($probe)
  $pg.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAlias
  $size = $pg.MeasureString($text, $font)
  $pg.Dispose(); $probe.Dispose()

  $w = [int][Math]::Ceiling($size.Width) + 2
  $h = [int][Math]::Ceiling($size.Height)

  $bmp = New-Object System.Drawing.Bitmap($w, $h, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
  $g = [System.Drawing.Graphics]::FromImage($bmp)
  $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAlias
  $g.DrawString($text, $font, [System.Drawing.Brushes]::White, 1, 0)
  $g.Dispose()

  # Same orientation as every other label: 90 CCW, reads bottom-to-top in landscape.
  $bmp.RotateFlip([System.Drawing.RotateFlipType]::Rotate270FlipNone)
  $file = Join-Path $outDir "$key.png"
  $bmp.Save($file, [System.Drawing.Imaging.ImageFormat]::Png)
  $entries.Add("  '$key': { src: 'images/labels/$key.png', w: $($bmp.Width), h: $($bmp.Height) },")
  $bmp.Dispose()
}

$font.Dispose()

$body = ($entries -join "`n").TrimEnd(',')
$ts = @"
// AUTO-GENERATED by tools/gen-tut-labels.ps1 -- do not edit by hand.
// Tutorial dialog line strips, pre-rotated like every other label. Importing
// this module registers them into the shared LABELS map.
import { LABELS, LabelInfo } from './labels.gen'

export const TUT_LABELS: Record<string, LabelInfo> = {
$body
}

Object.assign(LABELS, TUT_LABELS)
"@

Set-Content -Path $tsPath -Value $ts -Encoding UTF8
Write-Host "Wrote $($lines.Count) strips to images/labels and $tsPath"
